/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Ctrl_Usuario;
import util.ThemeManager;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelo.Usuario;

/**
 *
 * @author Adriel
 */
public class Register extends javax.swing.JFrame {
    
    int xMouse, yMouse;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    public Register() {
        ThemeManager.aplicarTemaGuardado();
        initComponents();
        this.setTitle("Registrarse");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
               configurarColores();
    }
    
        private void configurarColores() {
        Color bgColor = UIManager.getColor("Panel.background");
        Color fgColor = UIManager.getColor("Panel.foreground");
        
        background.setBackground(bgColor);
        
        // Labels
        jLabel1.setForeground(fgColor);
        jLabel2.setForeground(fgColor);
        jLabel3.setForeground(fgColor);
        jLabel4.setForeground(fgColor);
        jLabel5.setForeground(fgColor);
        jLabel6.setForeground(fgColor);
        jLabel7.setForeground(fgColor);
        
        // TextFields
        txt_nombre.setBackground(bgColor);
        txt_nombre.setForeground(fgColor);
        txt_apellidos.setBackground(bgColor);
        txt_apellidos.setForeground(fgColor);
        txt_nickname.setBackground(bgColor);
        txt_nickname.setForeground(fgColor);
        txt_correo.setBackground(bgColor);
        txt_correo.setForeground(fgColor);
        txt_password_registro.setBackground(bgColor);
        txt_password_registro.setForeground(fgColor);
        
        // Separadores
        Color borderColor = UIManager.getColor("Component.borderColor");
        jSeparator1.setForeground(borderColor);
        jSeparator2.setForeground(borderColor);
        jSeparator5.setForeground(borderColor);
        jSeparator6.setForeground(borderColor);
        jSeparator7.setForeground(borderColor);
    }

    private void RegistrarUsuario() {

        if (!txt_nombre.getText().isEmpty()
                && !txt_apellidos.getText().isEmpty()
                && !txt_nickname.getText().isEmpty()
                && !txt_password_registro.getText().isEmpty()
                && !txt_correo.getText().isEmpty()) {

            Usuario usuario = new Usuario();

            usuario.setNombre(
                    txt_nombre.getText().trim());

            usuario.setApellido(
                    txt_apellidos.getText().trim());

            usuario.setNickname(
                    txt_nickname.getText().trim());

            usuario.setPassword(
                    txt_password_registro.getText().trim());

            usuario.setCorreo(
                    txt_correo.getText().trim());

            Ctrl_Usuario controlUsuario
                    = new Ctrl_Usuario();

            if (controlUsuario.registrarUsuario(usuario)) {

                JOptionPane.showMessageDialog(
                        null,
                        "Usuario registrado correctamente"
                );

                limpiar();

            } else {

                JOptionPane.showMessageDialog(
                        null,
                        "Error al registrar usuario"
                );
            }

        } else {

            JOptionPane.showMessageDialog(
                    null,
                    "Complete todos los campos"
            );
        }
    }

    private void limpiar() {

        txt_nombre.setText("");
        txt_apellidos.setText("");
        txt_nickname.setText("");
        txt_password_registro.setText("");
        txt_correo.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_nickname = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_password_registro = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JPanel();
        btnRegisterText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 135, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Apellido:");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 195, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Usuario:");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 255, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Contraseña:");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 375, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Correo:");
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 315, -1, -1));

        txt_nombre.setBorder(null);
        txt_nombre.addActionListener(this::txt_nombreActionPerformed);
        background.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 285, 30));

        txt_apellidos.setBorder(null);
        background.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 285, 30));

        txt_nickname.setBorder(null);
        txt_nickname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        background.add(txt_nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 285, 30));

        txt_correo.setBorder(null);
        background.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 285, 30));

        txt_password_registro.setBorder(null);
        background.add(txt_password_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 285, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setText("Registrarse");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, -1, -1));

        btnReturn.setForeground(new java.awt.Color(0, 102, 204));
        btnReturn.setText("Volver");
        btnReturn.setBorder(null);
        btnReturn.setBorderPainted(false);
        btnReturn.addActionListener(this::btnReturnActionPerformed);
        background.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 495, -1, -1));

        jLabel7.setText("Ya tienes una cuenta?");
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 495, -1, -1));

        btnRegister.setBackground(new java.awt.Color(105, 115, 218));

        btnRegisterText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegisterText.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegisterText.setText("Registrarse");
        btnRegisterText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRegisterLayout = new javax.swing.GroupLayout(btnRegister);
        btnRegister.setLayout(btnRegisterLayout);
        btnRegisterLayout.setHorizontalGroup(
            btnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegisterText, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );
        btnRegisterLayout.setVerticalGroup(
            btnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegisterText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        background.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 435, 255, 45));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 285, -1));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 285, -1));
        background.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 285, -1));
        background.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 285, -1));
        background.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 285, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        Login login = new Login();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnRegisterTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterTextMouseClicked
        this.RegistrarUsuario();
    }//GEN-LAST:event_btnRegisterTextMouseClicked

    private void btnRegisterTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterTextMouseEntered
        btnRegister.setBackground(new Color(122, 133, 252));
    }//GEN-LAST:event_btnRegisterTextMouseEntered

    private void btnRegisterTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterTextMouseExited
        btnRegister.setBackground(new Color(105, 115, 218));// TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterTextMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnRegister;
    private javax.swing.JLabel btnRegisterText;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nickname;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_password_registro;
    // End of variables declaration//GEN-END:variables
}
